version: '2'
services:
  kaffeeautomat-app:
    image: kaffeeautomat
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://kaffeeautomat-mysql:3306/kaffeeautomat?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  kaffeeautomat-mysql:
    extends:
      file: mysql.yml
      service: kaffeeautomat-mysql
